/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  developer: [
    {
      type: 'category',
      label: '読み上げ',
      items: ['developer/speaker/ready', 'developer/speaker/main', 'developer/speaker/queue'],
      link: {type: "doc", id: "developer/speaker/about"}
    },
    {
      type: "category",
      label: "ロール付与ボタン",
      items: ["developer/role-button/main", "developer/role-button/custom-id"],
      link: {type:"doc", id: "developer/role-button/about"}
    }
  ],
  
};

module.exports = sidebars;
